baseURL = 'https://shmf-2024.netlify.app/'

languageCode = 'en-us'
title = 'Sleepy Hollow Music Festival'

theme = "SHMF2024"

[params]
    tagline = "Kingsland Point Park 06.07.2025"
    info = "KINGSLAND POINT PARK • 06.07.2025"
    description = "Home of the 2024 Sleepy Hollow Music Festival"
    header_logo_image = "/images/shmf-logo-hdr.png"
    email = "info@sleepyhollowmusicfestival.com"
    instagram = "https://www.instagram.com/sleepyhollowmusicfestival/"
    facebook = "https://www.facebook.com/sleepyhollowmusicfest"

[[menu.main]]
    name = "Info"
    pageRef = "/info"
    weight = "10"
    is_enabled = true
[[menu.main]]
    name = "Tickets"
    pageRef = "/tickets"
    weight = "20"
    is_enabled = true
[[menu.main]]
    name = "Artists"
    pageRef = "/artists"
    weight = "30"
    is_enabled = false
[[menu.main]]
    name = "Merch"
    pageRef = "/merch"
    weight = "40"
    is_enabled = true